title: Is Uberspace online?
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: /
params:
  alwaysKeepBrandColor: false
  autoRefresh: true
  brand: 181818
  customTabs:
    - link: 'https://uberspace.de/imprint'
      name: Legal Notice
    - link: 'https://uberspace.de/privacy'
      name: Privacy
    - link: 'https://twitter.com/ubernauten'
      name: Twitter
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: FF8C00
  down: DC143C
  incidentPostsPerPage: 3
  logo: /logo.svg
  notice: 708090
  ok: 228B22
  systems:
    - description: 'data center uvensys (185.26.156.0/25), Uberspace 6 and 7'
      name: FRA3
    - description: 'data center rh-tec (95.143.172.0/24), Uberspace 6'
      name: FRA2
    - name: olbers
    - name: encke
    - name: neujmin
    - name: kopff
    - name: betelgeuse
    - name: klemola
    - name: clark
    - name: corvus
    - name: fomalhaut
    - name: acamar
    - name: kohoutek
  useLargeHeaderDesign: true
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
